apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: cloudops
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: "cloudops-default"

    receivers:
      - name: "cloudops-default"
