apiVersion: v1
kind: Service
metadata:
  name: cloudops-frontend
  namespace: cloudops
  labels:
    app: cloudops-frontend
spec:
  type: LoadBalancer
  selector:
    app: cloudops-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80