apiVersion: v1
kind: Secret
metadata:
  name: cloudops-postgres-secret
  namespace: cloudops
type: Opaque
stringData:
  POSTGRES_DB: cloudops
  POSTGRES_USER: cloudops
  POSTGRES_PASSWORD: cloudops_dev_password