apiVersion: v1
kind: Service
metadata:
  name: cloudops-postgres
  namespace: cloudops
spec:
  type: ClusterIP

  selector:
    app: cloudops-postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP